syntax on
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set guifont=PragmataPro
set guioptions-=m
set guioptions-=T
set noesckeys
set relativenumber
set number
set ignorecase
set smartcase
set incsearch
set cinoptions=l1
set modeline
set iminsert=0
set imsearch=0
set autoindent
set autochdir
colorscheme habamax